ambrosia release oct 2020
JGCRI/ambrosia pull request #13
Opened 2020-10-11 06:19 UTC by kanishkan91

Final PR to merge in changes, clean ups for ambrosia October release

2020-10-13 18:53 UTC, crvernon requested changes
Excellent work!  

There needs to be a focus on consistent formatting throughout.  Especially in the formatting of the README and Vignette.  These are your first impression to the user and you want to come off very organized, consistent, and clean.  I made comments throughout but focus on cleaning up the README and Vignette. 

Consider the following:
- Pad spacing around commas, assignments, and operators for readability.
- Consistent variable and function name formatting.  Use lower case connected by an underscore for both.
- Single spaces between lines of code, double spaces between functions

2020-10-13 18:53 UTC, crvernon commented on DESCRIPTION
> +Depends: R (>= 3.5.0)
Did you paper say >=3.3?

2020-10-13 18:53 UTC, crvernon commented on R/calculate_ambrosia_parameters.R
> +calculate_ambrosia_params <- function(
bring the first argument up to the parenthesis

2020-10-13 18:53 UTC, crvernon commented on R/calculate_ambrosia_parameters.R
> +
[FOR ALL] only one line of whitespace between phrases, two between functions

2020-10-13 18:53 UTC, crvernon commented on R/calculate_ambrosia_parameters.R
> +    func_MC<-mc.setup(datadir)
[FOR ALL] space between function name and assignment.  For example (`fun_MC <- mc.setup(datadir)`)

2020-10-13 18:53 UTC, crvernon commented on R/calculate_ambrosia_parameters.R
> +    Raw_Data<-data %>%
[FOR ALL] lower case separated by an underscore for all variable and function names.

2020-10-13 18:53 UTC, crvernon commented on R/calculate_ambrosia_parameters.R
> +    Raw_Data<-data %>%
[FOR ALL] consistent spacing assignment of values to arguments (e.g. `rename(gdp_pcap_thous2005usd = gdp_pcap_thous)`

2020-10-13 18:53 UTC, crvernon commented on R/calculate_ambrosia_parameters.R
> +#' @author KBN 2020
[CHECK FOR ALL] No `@return` declared

2020-10-13 18:53 UTC, crvernon commented on R/calculate_ambrosia_parameters.R
> +    if(any(data$gdp_pcap_thous<0.1)){
[FOR ALL] spacing around operators and/or commas (e.g.,  `if(any(data$gdp_pcap_thous < 0.1)){`

2020-10-13 18:53 UTC, crvernon commented on R/calculate_ambrosia_parameters.R
> +    if(any(data$gdp_pcap_thous<0.1)){
What is `0.1` no comment explaining.  Should this be a variable?

2020-10-13 18:53 UTC, crvernon commented on R/calculate_ambrosia_parameters.R
> +        mutate(Ps= Ps*0.365, Pn= Pn*0.365, sig2Qs=pmax(lower_limit_sigma,sig2Qs)
explanation for `0.365`

2020-10-13 18:53 UTC, crvernon commented on inst/app/app.R
>  etasdefault <- c(-0.17, 0.17)
Comments about what these are

2020-10-13 18:53 UTC, crvernon commented on scripts/README.md
> +This folder contains functions that were used to create the figures for Edmonds et al. (2017).
Why are we still keeping this?  Should this be deleted since it has no relevance to our new version?

2020-10-13 18:53 UTC, crvernon commented on scripts/cpp/readme.md
> +# Running the GCAM food demand model from C++
is this needed?

2020-10-13 18:53 UTC, crvernon commented on tests/testthat/test_mc_analysis_functions.R
> +
remove extra whitespace

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +```{r}
don't execute these for the tutorial (e.g., change `{r}` to `r`

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +```{r}
remove `supressMessages` wrapper

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +This is an [R Markdown](http://rmarkdown.rstudio.com) Notebook. When you execute code within the notebook, the results appear beneath the code.
For the paper, It would be better to just set this up as a statically formatted notebook without dynamic execution.

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +c(1.28,1.14,-0.19,0.21,-0.33,0.5,0.1,16,5.06,100,20)->original_param_vector
[FOR ALL] change `{r}` to `r'

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +c(1.28,1.14,-0.19,0.21,-0.33,0.5,0.1,16,5.06,100,20)->original_param_vector
This example needs clean comments and whitespace around your commas and assignments.

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +Food_Demand$Total_Demand<-Food_Demand$Qs+Food_Demand$Qn
comments

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +
remove extra space

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +    # ggtitle("Calculated income elasticities for each level of income")+
[FOR ALL] remove any commented out code

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +## Example 5:Calculate income elasticities
need consistent one or two spacing after `:` for examples

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +#calc1eps returns a matrix of elasticities where the matrices are elasticities for staples(matrix 1), cross price elasticities(matrix 2,3),non_staple elasticities(matrix 4))
evenly spacing needed

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +Sample_Data <- read.csv("Training_Data.csv")
This will fail if I am not using it from the vignette.  Change `Training_Data.csv` to live as package data and call it accordingly from `ambrosia`

2020-10-13 18:53 UTC, crvernon commented on vignettes/ambrosia_vignette.Rmd
> +---
Instead of having the examples continue for each Part, change this in part reference.
For example,
```
Part 4:  Exploring data from a MCMC calculation
Example 4.1:  Read in `mc.data` and create density plots
```

2020-10-13 18:53 UTC, crvernon commented on README.md
> +```r
Under examples, pull out the first comment "# A list of examples describing the different features in `ambrosia`are described in the ambrosia_vignette.rmd in the vignettes folder. The example below shows how a user can get an estimate of demand using some sample parameters." in the R code block and place it in a markdown cell.

For example:

## Examples
 A list of examples describing the different features in `ambrosia` are described in the `ambrosia_vignette.rmd` in the vignettes folder. The example below shows how a user can get an estimate of demand using some sample parameters.  

```r
# get a sample data set
test_data <- data.frame(Y=seq(0.1,30, by=0.1))

# add sample values of Ps and Pn
test_data %>% mutate(Ps=0.1, Pn=0.2) -> test_data

# add some sample parameters
sample_parameters <- c(1.28, 1.14, -0.19, 0.21, -0.33, 0.5, 0.1, 16, 5.06, 100, 20)
```

2020-10-14 01:13 UTC, kanishkan91 commented on DESCRIPTION
> +Depends: R (>= 3.5.0)
I have tried with an updated R version. So I think 3.5 should be fine. Does that sound OK?

2020-10-14 01:14 UTC, kanishkan91 commented on R/calculate_ambrosia_parameters.R
> +calculate_ambrosia_params <- function(
Done

2020-10-14 01:31 UTC, kanishkan91 commented on scripts/README.md
> +This folder contains functions that were used to create the figures for Edmonds et al. (2017).
I just corrected the explanation. This folder contains functions that can be used to calculate the training data used for generating parameter values for GCAM. This is also referenced in the paper. It is relevant for users interested in regenerating parameters used in GCAM and is kept in since this is mentioned as one of the main motivations to create ambrosia. Let me know what you think of this.

2020-10-14 01:34 UTC, kanishkan91 commented on scripts/cpp/readme.md
> +# Running the GCAM food demand model from C++
I think so. Once again, this is explained in the paper as well. (I have also corrected the explanation in the .md file). Basically the user can use the maximization approach implemented in R or they can also use their own fitting approach using a log likelihood function setup using ambrosia. This is an example of fitting a MCMC in C++ using a log likelihood function set up in R. Also referenced in the vignette.

2020-10-14 01:38 UTC, kanishkan91 commented on vignettes/ambrosia_vignette.Rmd
> +```{r}
Done. Thanks!

2020-10-14 01:44 UTC, kanishkan91 commented on vignettes/ambrosia_vignette.Rmd
> +This is an [R Markdown](http://rmarkdown.rstudio.com) Notebook. When you execute code within the notebook, the results appear beneath the code.
Changed. Thanks!

2020-10-14 03:12 UTC, crvernon commented on DESCRIPTION
> +Depends: R (>= 3.5.0)
@kanishkan91 sounds good to me

2020-10-14 04:33 UTC, kanishkan91 commented on README.md
> +```r
Updated

2020-10-14 04:39 UTC, kanishkan91 commented on vignettes/ambrosia_vignette.Rmd
> +---
Done. Thanks!

2020-10-14 04:39 UTC, kanishkan91 commented on vignettes/ambrosia_vignette.Rmd
> +Sample_Data <- read.csv("Training_Data.csv")
I have taken out all datasets. I am loading them all as package data instead. .gitignore is also updated to ignore any temporary outputs that the user may generate

2020-10-14 04:48 UTC, kanishkan91 commented on vignettes/ambrosia_vignette.Rmd
> +## Example 5:Calculate income elasticities
Done. Thanks!

2020-10-14 04:48 UTC, kanishkan91 commented on vignettes/ambrosia_vignette.Rmd
> +#calc1eps returns a matrix of elasticities where the matrices are elasticities for staples(matrix 1), cross price elasticities(matrix 2,3),non_staple elasticities(matrix 4))
Done. Thanks!

2020-10-14 04:55 UTC, kanishkan91 commented on inst/app/app.R
>  etasdefault <- c(-0.17, 0.17)
Added comments that these are default values for the shiny application

2020-10-14 04:55 UTC, kanishkan91 commented on R/calculate_ambrosia_parameters.R
> +        mutate(Ps= Ps*0.365, Pn= Pn*0.365, sig2Qs=pmax(lower_limit_sigma,sig2Qs)
Added comment explaining what that is

2020-10-14 04:57 UTC, kanishkan91 commented on R/calculate_ambrosia_parameters.R
> +    if(any(data$gdp_pcap_thous<0.1)){
This is documented. If there is an income of less than 0.1, no budget can be assigned and implies subsistence farming. There is also a test under test_that that checks for this.

2020-10-14 04:58 UTC, kanishkan91 commented on R/calculate_ambrosia_parameters.R
> +#' @author KBN 2020
return declared for all functions. In some cases it is declared before param since the return requires explanation in case of big data frames returned

2020-10-14 16:02 UTC, crvernon approved these changes

2020-10-14 23:42 UTC, kanishkan91 commented on R/calculate_ambrosia_parameters.R
> +
Updated.

2020-10-14 23:42 UTC, kanishkan91 commented on R/calculate_ambrosia_parameters.R
> +    func_MC<-mc.setup(datadir)
Updated

2020-10-14 23:42 UTC, kanishkan91 commented on R/calculate_ambrosia_parameters.R
> +    Raw_Data<-data %>%
Updated

2020-10-14 23:50 UTC, merged